name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: photonquantum/stargazer-subscriber-backend
          username: ${{ secrets.PQ_DOCKER_USERNAME }}
          password: ${{ secrets.PQ_DOCKER_PASSWORD }}
